set encoding=utf-8
set fileencodings=utf-8,cp950
set nocompatible
syntax on
set number
set expandtab
set shiftwidth=4
set tabstop=4
set hlsearch
set incsearch
set ic
set autoindent
set cursorline
"colorscheme torte
colorscheme desert 
