# Generated by Django 3.1.1 on 2020-09-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceid', models.IntegerField()),
                ('logged_datetime', models.DateTimeField()),
            ],
        ),
    ]
