# Generated by Django 3.1.1 on 2020-09-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='ac_output_power',
            field=models.IntegerField(default=0),
        ),
    ]
