PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE pvlog (ID INTEGER, BRAND TEXT, WATT INTEGER, KWH INTEGER);
INSERT INTO "pvlog" VALUES(1,'Ablerex',10,1200);
INSERT INTO "pvlog" VALUES(2,'Ablerex',10,1200);
INSERT INTO "pvlog" VALUES(3,'Delta',10,1200);
INSERT INTO "pvlog" VALUES(4,'Others',10,1200);
COMMIT;
